### ISSUE TITLE
Please provide a service change history

### ISSUE THREAD

**Issue by occasionallydavid** [finnhubio/Finnhub-API#102]
(Paying user)

Please consider adding a more formal change history for the service and data. I see already you are doing very well with API announcements on GitHub, that's wonderful, but I notice e.g. in #98 quite significant material data changes being made that aren't really sufficiently described, even when queried -- some of these data values vary by 0.5%.

I deeply appreciate the service you're offering, and I really hope you succeed with it, but creating a little more transparency around changes like this would do wonders for improving trust.

**Comment by Bailey-1** [comment]
It would also be great if it included changes to the API plans such as moving routes from the free tier to the paid tier and weight adjustments. Like when did company profile move to the premium tier and have the weight doubled? Shame because I was using that. 

I understand that you don't want to advertise changes in advance because people will obviously take advantage of that but it would be great if there was at least a record of the changes after to ensure I'm not imagining things. Thanks.

**Comment by finnhubio** [comment]
After April 15th, everything will be stable and documented. For now, the API is still under active development and we are discussing with our new investors about the direction of the company. 

A change history will be available on the documentation this month. Thank you for the feedback
