### ISSUE TITLE
Can we get Dow Jones?

### ISSUE THREAD

**Issue by Brechard** [finnhubio/Finnhub-API#228]
Hi! Is it possible to get the Dow Jones candles? I cannot find a symbol for that

**Comment by finnhubio** [comment]
Try ^DJI

**Comment by Brechard** [comment]
that worked, thanks!

**Comment by greatBigDot** [comment]
That doesn't work for me. https://finnhub.io/api/v1/quote?symbol=^DJI&token=MY_TOKEN  just yields `{"error":"Symbol not supported."}`. (It doesn't seem to be an issue of HTML encoding either; swapping `%5e` in for the caret doesn't change anything.)

It's a bit of a shame, since accessing the Dow Jones is the main thing I got a Finnhub API key for, but it's the one thing that doesn't work!
