### ISSUE TITLE
Missing stock data

### ISSUE THREAD

**Issue by aakins57** [finnhubio/Finnhub-API#57]
I'm trying to get data by the minute for certain stock symbols and am seeing holes in the data set.  The URL below is for SPY data from 2/10/20-2/21/20.  The data set looks fine for the first week but I only see partial data on 2/19 then no data on 2/20 and 2/21.

The data on 2/19 is only for the first few hours of the day then stops.  (2/17 was a holiday so I do not expect to see data from that date).  Since it seems like the data flow stops at a certain point (morning of 2/19) does the API call only run for a certain amount of time before it stops pulling data or am I limited on the amount of records I can pull since I'm using the free version?

https://finnhub.io/api/v1/stock/candle?symbol=SPY&resolution=1&from=1581343200&to=1582322400&token=

**Comment by 0x2b543c** [comment]
I'm experiencing a similar issue. I'm trying to get 30M resolution data for TSLA, SPY, and others but am receiving large holes in the data set. 

For example if I make a call for SPY and set the start date to 2020-01-01 (and converting to UNIX timestamp for the actual call) it returns data from 1/1 through 1/9 and then jumps from 1/9 to 3/24. If I set the start date to 2020-02-01 it gives me data from 2/1 through 2/10 and then jumps to 3/2.

I thought it was because I was using the free plan so I upgraded to the basic plan and am still having the same issue.

**Comment by monism123** [comment]
this is the same issue as https://github.com/finnhubio/Finnhub-API/issues/56

**Comment by aakins57** [comment]
I don't see a resolution with that issue in the thread.  Seems like this is an ongoing issue, is there any fix for it?

**Comment by finnhubio** [comment]
We are aware of some issues with deep historical US candle data. We are currently migrating the data to a new database to eliminate these issues. ETA : end of next week. We will keep everyone up to date.

**Comment by finnhubio** [comment]
The issue has been fixed

**Comment by pesapower** [comment]
I have a similar [issue 226](https://github.com/finnhubio/Finnhub-API/issues/226).
